### ISSUE TITLE
data-defaultsort can impact django  locale setting

### ISSUE THREAD

**Issue by HackToday** [drvic10k/bootstrap-sortable#100]
I have django project which set LANGUAGE_CODE = 'zh-hans'
and then when I set table sortable with following attribute

```
<th style="" data-defaultsort="asc"> something</th>
```

The bootbox  confirm box button would have english  'Cancel' and 'OK'

if I remove data-defaultsort attriibute, like below

```
<th style="" > something</th>
```

The  bootbox confirm button would have locale style which means chinese . So it seems `data-defaultsort` attribute have something issue to impact other not work

**Comment by drvic10k** [comment]
this is interesting, but I cannot really do much about it
