### ISSUE TITLE
bootstrap-sortable need update

### ISSUE THREAD

**Issue by HackToday** [drvic10k/bootstrap-sortable#101]
As https://github.com/Sjeiti/TinySort have more updates and fixes,  for example.  https://github.com/Sjeiti/TinySort/issues/102

But bootstrap-sortable not updated for long time.

So it is better  for bootstrap to add new support for the tinysort versions

**Comment by drvic10k** [comment]
thanks, I will update

**Comment by marcreig** [comment]
Needs TinySort update and also, needs to solve all the issues existing from March...

We all understand you did this "for the love of art" and for that, we can't demand you anything. But your plugin got quite popular and so you've a responsability about it.
If this is not the case anymore, simply just close the project and announce you're finished with it.
This way, we'll be able to refactor our code to something more mature like, [DataTables](https://datatables.net/examples/styling/bootstrap.html), i.e.
