### ISSUE TITLE
Possible to keep one row content not changed when sort another row?

### ISSUE THREAD

**Issue by HackToday** [drvic10k/bootstrap-sortable#104]
I have one requirement, to my understanding, bootstrap-sortable can not do that. However, it would be more helpful get more inputs what can achieve that. or maybe bootstrap-sortable could do that just I not know.

For example I have following table: column which is `row number` `app name` and `cluster name`

+--+--+--+--+--+
| 1 | app1 | cluster1 | 
+--+--+--+--+--+
| 2 |  app2 | cluster2  |
+--+--+--+--+--+
| 3 | app3 | cluster3 |
+--+--+--+--+--+
|  4|  app4| cluster4 |
+--+--+--+--+--+

**when sort as app name,  the row number also changed.
Is it possible to sort app name while keep row column not changed ?  Like below**

+--+--+--+--+--+
| 1 | app4 | cluster4 | 
+--+--+--+--+--+
| 2 |  app3 | cluster3  |
+--+--+--+--+--+
| 3 | app2 | cluster2 |
+--+--+--+--+--+
|  4|  app1| cluster1 |
+--+--+--+--+--+

If sortable could not do that, what's the possible way to do that? (Be clear, we still need sortable, because we need to sort other columns)

**Comment by HackToday** [comment]
Seems `tablesorter` can do that like this mentioned in https://github.com/Mottie/tablesorter/issues/616

It would be great if `bootstrap-sortable` can also implement such feature

**Comment by HackToday** [comment]
My mistake, the Mottie/tablesorter#616 was two tables , not real table itself support

**Comment by drvic10k** [comment]
that was actually one of my proposals

create 2 tables, one for the first column and style them so they look as one table

the second proposal is to hook on the `sorted` event and refresh the first column

**Comment by HackToday** [comment]
For 2 tables, it is not that ok. as it we use bootstrap tables. for that cases, the right table width and height can dynamically changed. While first table not know about it. Thus that can cause two tables align in mess for such cases

For second way, I need to check the sorted event if possible to achieve that

**Comment by HackToday** [comment]
@drvic10k  also I did not find Documentation about how to use event, or any code example

**Comment by HackToday** [comment]
Finally, I managed to use sorted event
