### ISSUE TITLE
Table inside table issue

### ISSUE THREAD

**Issue by KrunchMuffin** [drvic10k/bootstrap-sortable#105]
V2.0.1 I have a sortable outer table, with non-sortable inner table. the inner only shows when I click a details button. When open and I sort the outer table, the inner table content does not change. Is there a way to rectify that?

**Comment by drvic10k** [comment]
why should the inner table content change when you sort the outer table?

**Comment by KrunchMuffin** [comment]
Sorry I didn't word that appropriately. I have a sortable table and each row has a non sortable table inside.

**Comment by drvic10k** [comment]
if you don't specify `data-value` for the cell, it's taken as the text of the cell, which in this case is not very useful
so if you want to sort it in some meaningful way, it would be best to set the `data-value` attributes by yourself

**Comment by drvic10k** [comment]
is this till valid?

**Comment by KrunchMuffin** [comment]
well ya,  but I don't think ur understanding or I am not explaining it correctly.

**Comment by KrunchMuffin** [comment]
I will see if I can get sample up
