### ISSUE TITLE
Is it possible to fors sort as string for all columns?

### ISSUE THREAD

**Issue by webjohan** [drvic10k/bootstrap-sortable#115]
When testing this plugin out on a page that has two ajax updated tables it looks like you have to use moment.js to get everything to work. When some columns have time stamps in the form hh:mm:ss.
Is it possible to force stort as string?

**Comment by drvic10k** [comment]
it should only sort as date if you specify the format, otherwise it's used as a string

**Comment by webjohan** [comment]
Nope. It looks like tinysort tries to sort it as date/time.
I found how to force tinySort to force use of string sorting:
tinysort.defaults.forceStrings = true;

**Comment by webjohan** [comment]
I'll close this issue. 

Future improvement might include a setting for this?
