### ISSUE TITLE
thead-dark results in text vanishing on hover

### ISSUE THREAD

**Issue by LwsBtlr** [drvic10k/bootstrap-sortable#124]
Given this thead in a bootstrap file using sortable:

```
<thead class="thead-dark">
  <tr>
    <th>Title</th>
     <th>Year</th>
     <th data-defaultsort="desc">Score</th>
     <th data-defaultsort='disabled'>Link</th>
     <th data-defaultsort='disabled'>Adress</th>
  </tr>
</thead>
```

When you hover over the columns that are sortable (Title and Year and Score) the text vanishes.

**Comment by drvic10k** [comment]
what classes do you have on the table? I couldn't reproduce this issue in my demo, when I just added the class to `<thead>`
