### ISSUE TITLE
Date sorting error 

### ISSUE THREAD

**Issue by NeuralLink** [drvic10k/bootstrap-sortable#18]
Related to Issue 13.

Here is the output:

7/31/2013
7/31/2013
7/30/2013
8/23/2013
8/23/2013
8/1/2013
12/30/2013
12/30/2013
12/21/2013
12/21/2013
12/21/2013 

As you can see, there are a number of errors with the sorting.

Here is what my HTML looks like:

```html
<td data-dateformat="M-D-YYYY">
    @item.EndDate.ToShortDateString()
</td>
````
I'm using the current version on nuGet (1.4.0)

**Comment by dflow** [comment]
@NeuralLink  did you manage to find the conflict?
I am having a similar issue with
```
<th data-dateformat="YYYY-MM-DD" data-defaultsign="month">Day</th>
```
data is sorted according to the DD value.
![screen shot 2015-03-03 at 11 00 58 am](https://cloud.githubusercontent.com/assets/1641750/6459166/b4def7ba-c194-11e4-8d67-88b3fd467216.png)
![screen shot 2015-03-03 at 11 00 09 am](https://cloud.githubusercontent.com/assets/1641750/6459167/b9b8c766-c194-11e4-9075-03d0e338ba0e.png)

**Comment by NeuralLink** [comment]
No, my client considered it a trivial bug and didn't want me to spend any extra time on it.

**Comment by dflow** [comment]
hi @drvic10k

do you have a solution for this?

**Comment by drvic10k** [comment]
can you post, how the HTML looks like after table is initialized? what are the data values, that are generated?

**Comment by dflow** [comment]
hi @drvic10k

it seems to have worked out
thanks

**Comment by drvic10k** [comment]
can you post what was the problem, so that others with similar problem can find the solution?

**Comment by dflow** [comment]
I posted above with screenshots

**Comment by drvic10k** [comment]
yes, but I thought that you found the origin of the problem
or it just disappeared?

**Comment by dflow** [comment]
it disappeared , I couldn't reproduce it.

**Comment by JC5** [comment]
I've had similar problems with date sorting. I can't for the life of me figure out which data-dateformat I should use:

``<td data-value="2015-01-01">1 January 2015</td>``

Would it be:

``<th data-dateformat="YY-MM-DD">Date</th>``

Or

``<th data-dateformat="D MMMM YYYY">Date</th>``

In the end I used this:

``<td data-value="(unix timestamp here)">1 january 2015</td>``

**Comment by drvic10k** [comment]
The data-dateformat should define the format in which the value in the cell is provided, so fot your case, it would be `"D MMMM YYYY"`
