### ISSUE TITLE
Live content with ajax

### ISSUE THREAD

**Issue by emmgfx** [drvic10k/bootstrap-sortable#32]
How I can apply the effects to a table dynamicaly loaded?

**Comment by sheamf** [comment]
This solved my problem, so I thought I'd add a little more detail for others with the same issue.  After updating a sortable table via ajax, the `<th>` elements weren't rendering with the `data-sortcolumn` or `data-sortkey` attributes, and trying to sort a column caused this error: `Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': 'td:nth-child(NaN)' is not a valid selector.`.  

Adding `$.bootstrapSortable(true);` to my `complete` callback fixed it, and now those attributes are present on the table headers.

**Comment by mohamadwp8** [comment]
$.bootstrapSortable(true);
thank my problem solved
