### ISSUE TITLE
Empty columns are being "sorted" in Chrome

### ISSUE THREAD

**Issue by wired9** [drvic10k/bootstrap-sortable#40]
In a table with a sortable column of empty values (&lt;td&gt;&lt;/td&gt;) sorting still happens after clicking on the column header, causing rows to reorder, which is somewhat confusing.
This happens only in Chrome (tested in Firefox, Chrome and Safari)

**Comment by drvic10k** [comment]
sorry for the lond delay

TinySort author released a fix for this issue, so I will update to the newest version and try if it works
