### ISSUE TITLE
Not sorting check box column . Want to sort checkbox which are checked

### ISSUE THREAD

**Issue by vish02chouhan** [drvic10k/bootstrap-sortable#43]
I created a table in which first column is of check boxes . Now i want to this column with check boxes which are checked . I also updating data-value from 0 to 1 when some one check check box , but this is not working

**Comment by drvic10k** [comment]
is this issue stil valid?

**Comment by vish02chouhan** [comment]
Problem is solved for me now.. Thanks for checking with me ...

**Comment by drvic10k** [comment]
no problem
