### ISSUE TITLE
MaxCDN version

### ISSUE THREAD

**Issue by niftylettuce** [drvic10k/bootstrap-sortable#45]
@jdorfman please add this to maxcdn

**Comment by drvic10k** [comment]
ok, so I did a pull request to jsdelivr, now I'm waiting for the merge

**Comment by drvic10k** [comment]
forgot to update here, it's now available on jsdelivr: http://www.jsdelivr.com/#!bootstrap-sortable

**Comment by julianxhokaxhiu** [comment]
Awesome!

**Comment by krassowski** [comment]
Does not work for me, the link above just redirects to: https://www.jsdelivr.com/package/npm/bootstrap-table. Why is that?

**Comment by krassowski** [comment]
Though:
https://cdn.jsdelivr.net/gh/drvic10k/bootstrap-sortable@2.1.0/Scripts/bootstrap-sortable.js
https://cdn.jsdelivr.net/gh/drvic10k/bootstrap-sortable@2.1.0/Scripts/bootstrap-sortable.min.js
work :)
