### ISSUE TITLE
Sorting and colspam

### ISSUE THREAD

**Issue by Paul0079** [drvic10k/bootstrap-sortable#49]
I've read the following:
> *Cell with colspan and multiple header rows*

> When you have cell with colspan, by default, the first column of the span will be sorted. You can override this by using data-mainsort attribute for the column that you want to be sorted with the colspan cell.

However I don't get the following working:

    <table class="table table-bordered sortable">
    <thead>
    	<tr class='active'>
    		<TH class='text-center' colspan=2>Gift name</TH>
    		<TH class='text-center'>Gift type</TH>
    	</tr>
    </thead>
    
    <tbody>
    	<td class='hidden-xs' width=1%>
			<a href="http://www.steamgifts.com/giveaway/mScH1/cubemen-2"><img src='http://cdn.akamai.steamstatic.com/steam/apps/295850/capsule_sm_120.jpg'></a>
    	</td>
    	<td data-mainsort><a href="http://www.steamgifts.com/giveaway/mScH1/cubemen-2">Cubemen 2</a></td>
    	<td>Bundle game</td>
    </tbody>
    </table>

The sorting is just not working when I put a 'colspan' on the TH header.

**Comment by mikla** [comment]
+1
