### ISSUE TITLE
Suggestion: Do not sort the last row

### ISSUE THREAD

**Issue by Khrysller** [drvic10k/bootstrap-sortable#53]
Suggestion: I have a table and the last row is the Total row. When I sort the Total row is sorted too. The ideal behavior is to keep the Total row freezed.

Today is it possible to have this?

**Comment by cvrebert** [comment]
Wouldn't you use `<tfoot>` for that kind of thing?

**Comment by drvic10k** [comment]
so is the `<tfoot>` solution enough for your needs?

**Comment by Khrysller** [comment]
Gonna try this on monday. Thanks.

**Comment by Khrysller** [comment]
Works! Thanks.
