### ISSUE TITLE
Disable row

### ISSUE THREAD

**Issue by bryceadams** [drvic10k/bootstrap-sortable#58]
Hey! I know there's already this closed issue https://github.com/drvic10k/bootstrap-sortable/issues/50 - but it doesn't apply here.

I have a table where a certain row will dynamically be added underneath a certain row. I don't want this row to be sorted though, so I'd like it to maintain it's position underneath that certain row regardless of any sorting. Hope that makes sense :)

**Comment by drvic10k** [comment]
It makes sense, but doesn't look to be easily achieved :)
I plan to work on issues this weekend, so I will update here, if I can think of a good solution.

**Comment by bryceadams** [comment]
Thank you :) Yes, I know it's a bit tricky haha. One thought I had was to set the data value to be the same as the previous row but in this case, it's a colspan for 6 td's so it will only work when the first column is used to sort the table. And even then, it doesn't work the opposite direction :P

**Comment by drvic10k** [comment]
there's a `before-sort` event raised, you can remove the row there and then add it back in `sorted` event callback

**Comment by bryceadams** [comment]
That's a really good idea. Will try tonight :)



Best,Bryce

**Comment by karwalbubble** [comment]
This resolved my issue.
