### ISSUE TITLE
Sort blank columns last

### ISSUE THREAD

**Issue by alexjurkiewicz** [drvic10k/bootstrap-sortable#59]
Hello, nice js script! It's very robust :) My problem is: I have some columns with blank data in some cells. Currently these sort before any other value(?) but I'd like them to always sort to the bottom instead. Could support for this be added?

**Comment by drvic10k** [comment]
sorry for the dalay, i forgot to reply, but I asked in the sorting engine repo, if it is possible to do in an easy way

**Comment by drvic10k** [comment]
so the sorting engine was updated, now it is possible to sort with empty values at the end
but it's at the end of the alphabet, so when you sort descending, they are first

now I'm not sure, if this is what you wanted

**Comment by alexjurkiewicz** [comment]
Hi Matus, thanks for the update! Personally, I'd like empty values to sort
last when ascending or descending, but this is definitely better [?]

**Comment by drvic10k** [comment]
I just got an idea

if sorting ascending, then I could sort the empty cells last and when sorting descending, sort them first, so they are at the end again

**Comment by alexjurkiewicz** [comment]
Simple is good :-)

**Comment by Khrysller** [comment]
Related to #70

**Comment by drvic10k** [comment]
it's not really related to #70, because you want to change the order of all rows except the blank ones
