### ISSUE TITLE
General Inconsistency

### ISSUE THREAD

**Issue by quemelol** [drvic10k/bootstrap-sortable#61]
Hi, I've decided to use this plugin from all the existing others because it's small, useful and works "out-of-the-box".

But it has some problems:

1) If you have an static HTML (php page) with some sortable tables, and call the:

jQuery(function(){

...
	$.bootstrapSortable(true, 'reversed');
...

on the JS part, all the tables get correctly sorted. Right?

Well, the via AJAX I add some new tables with sortable class, and I've to call again $.bootstrapSortable() to make it workable.
This doesn't work.
New attached table (response from ajax call) have no sort signs (and have default-sort on TH). This happens if I use $.bootstrapSortable(TRUE,...).
but if I use $.bootstrapSortable(False, ...) it works OK!

Problem with that?

I've a most dificult scenario:

- One page which have a sortable table static on request time, where every row of it as some action buttons which make an ajax call which brings and attach a table with response data. This table is sortable too. Problem here?

If I sort the static table (the one containing the buttons to ajax actions) and then I click a button and it adds a table on an other part of the same page, as I've called the $.bootstrapSortable with FALSE, it reorders the main table and this is not what I want.
So if I change it to TRUE, this particular case works right, but the same "attachement function after ajax post" that is generic on my framework (same ajax call for some type of forms on my framework) which call some php script and adds response to attach-selector node) has problems then on other cases, like for example the very first case explained.

It's hard to transmit the thing but the case is that it doesn't work properly and I guess that if instead of RESORT every sortable table every time you call $.bootstrapSortable, you could select which table you want to sort (for example, only added via AJAX tables), it would be enough.

Is it possible to specify which tables to sort instead of all the existing ones when you've added something on the fly?

**Comment by quemelol** [comment]
SCENARIO 1:

- Page with sortables tables.
- document.ready, calls $.bootstrapSortable(true)
- Via button and ajax call, you add a new table on the screen.
- You call $.bootstrapSortable(true) after ajax.
- It doesn't work.
- Instead you call $.bootstrapSortable(false) after AJAX and it works right.

SAME FUNCTION TO ADD SOMETHING CALLED VIA AJAX ON SCREEN IS USED FOR NEXT SCENARIO, SO IF IT'S $.bootstrapSortable(TRUE) it is for all the other screens and cases in the framework!

SCENARIO 2:

- Sortable table on page.
- Has buttons which calls AJAX function to attach some sortable tables on other part of screen.
- You sort somehow the main table and push a button.
- New table appears via ajax.
- Call $.bootstrapSortable(FALSE) - as it was false to make it work the SCENARIO 1.
- Sorts OK new table but main table loses sorted rows sort!
- Instead, you call it $.bootstrapSortable(TRUE) after AJAX call, and everything works OK, but then I lose SCENARIO 1!!!!!

**Comment by drvic10k** [comment]
I tried to add a table and then sort using $.bootstrapSortable(true) and it sorted also the new table

can you please post the raw HTML of the table you add?

**Comment by quemelol** [comment]
Yes! I know, but the problem is tha teven it sorts the new table what I don't want is that it sort the first table, the existing one!

Thing is that I have a table. I use the THs to sort it and then I add a table to same page dinamically via AJAX. As I call, $.bootstrapSortable(false) it "unsorts" the first table, the existing one from the beggining.

You would say "call $.bootstrapSortable(true)", no?
But I can't! Because this $.bootstrapSortable is from a JS function which is common in multiple places, I use it everywhere. And if I let it on $.bootstrapSortable(true), the problem I have is with another page from another module on the aplication, where when I add a table dinamically via AJAX, it appears as a sortable one, but it doesn't put the sort signs on THs! I mean, the new table on this new page is sortable when I add it via AJAX, but i doesn't have the signs on THs!

That's why I was asking if it is possible to specifically sort only the added tables via AJAX, and not all the existing ones in the page!

**Comment by quemelol** [comment]
I guess it is releated with the fact that, if you never sorted a table before (using TH's) and call $.bootstrapSortable(true), as there is no previous existing sort to be keept it fails somehow adding the sort signs on THs. But this only happens on tables added via AJAX dinamically on page. With existing ones on serving time, there is no problem at all. Sort signs appear normally.

- Normal page with sortable table html on it.
- On document.ready, call $.bootstrapSortable(true) or $.bootstrapSortable(false), doesn't mind. I do that, because I want the reversed symbols as default sort direction is incorrect for me.
- The via AJAX, add a sortable table on same page and of course, inmediatly after the ".html(data);" I call $.bootstrapSortable(true). TRUE, because with tha main table I probably sorted it, and want to keep this sort. As if I call $.bootstrapSortable(false), I lose the sort on the main table because it default-re-sorts all existing tables on page (main + added).

**Comment by drvic10k** [comment]
OK, so I think I understand. But I cannot simulate it, it works for me. I added the table by editing the HTML in chrome, which should be the same as adding the table via AJAX. And then I called $.bootstrapSortable(true)

I think the problem might be in the HTML for the table, that you are adding, can you please post it in the comment, so I can have a look at it?

**Comment by quemelol** [comment]
Goodmorning!

The code itself is very simple, normal table. Check this:

<table class="table table-striped sortable">
					<thead>
						<tr>
							<th data-defaultsort="desc">Received</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>...</td>
						</tr>
					</tbody>
				</table>

You see: thead, tbody, just one TH to test with one simple tr+td. Simple table to test, but I have the problem.

Look the scenario is next:

- HTML with one full table wich has some rows on it.
- Sortable table. So when document ready, I call $.bootstrapSortable(false, 'reversed'). False, because I want to sort, and show signs on THs reversed and no previous sorting has been made, as it is on document.ready.
- Table shows normally, and sorted and is sortable and displays sort signs on ths normally.
- Now, this table rows has forms with buttons. Those buttons execute ajax call which basically attach an HTML table to another part of the same screen. This table has to be SORTABLE so after doing $(...).html(data) on ajax.success, I obiously have to call $.bootstrapSortable(false, 'reversed') again.
- BUT, with FALSE as I shown, it works right. New table appears and is sortable and HAS SORT SIGNS ON THs. But as you can imagine, if I sort the main table, the one who calls ajaxs actions, as soon as I call another ajax action which attaches a sortable table, because I call $.bootstrapSortable(false, 'reversed') on succes part after attaching, main table gets resorted to its default state.
- I don't want this. I want to make new attached table sortable with signs reversed, but once done, to not to lose the main table sort that I could have made! So the way I should operate is to call $.bootstrapSortable(TRUE, 'reversed') instead, after ajax.success table attaching via .html(), isn't it?
- Well if you do so, the new table attaches normally, IT IS SORTABLE but display NO SORT SIGNS on THs! That is exactly the problem!

And there is no more to say. Normal code, normal HTML, normal ajax, normal ALL!
Somehow, you manage the "previous sorting" existing and something probably happens when it is true and no previous sorting was existing... I'm pretty sure it is a bug, as long as I don't see what I could be doing wrong... :(

**Comment by drvic10k** [comment]
the table that you posted has no class set

try it on my demo page: add the table on the page by editing the HTML and then run the JS from console and see if it works

**Comment by quemelol** [comment]
Yes it have. It is this forum which take things away.
Check this:

![captura](https://cloud.githubusercontent.com/assets/11758056/7019834/3e0f29fc-dd14-11e4-9e9b-7eebbf6bd3c8.PNG)

**Comment by quemelol** [comment]
Ok I've done it on your demo page and it doesn't work too!!!

I've just pasted the code on your page, adobe the buttons just to find a simple place.
Just pasted, and then on console launched $.bootstrapSortable(TRUE, 'reversed').

Pasted table gets sortable but has no signs!

![captura](https://cloud.githubusercontent.com/assets/11758056/7019926/1ccf3fb0-dd15-11e4-971d-d98d9ffad243.PNG)

But it's sortable and on the very moment I click TH to sort, then sign appears!

![2](https://cloud.githubusercontent.com/assets/11758056/7019932/2f873a72-dd15-11e4-80d2-88c3f2d01e22.PNG)

You see?

**Comment by drvic10k** [comment]
ok, finally I can reproduce it, now I can have a look at it

**Comment by quemelol** [comment]
Nice!
Hope to listen from you pretty soon!
Oh and can I make a suggestion?
Could you add the selector as a parammeter?
I would solve this problem just adding the selector on the function, en instead of doing:

$("table.sortable").each(...);

I would do $(selector).each(...);

This way you could decide which tables apply the sorting ability, and of course, after adding something via AJAX, you could apply $.bootstrapSortable(TRUE, 'reversed') only to new attached tables.

And would be even nice to instead of parametrizing the selector, making $.bootstrapSortable(TRUE, 'reversed') directly aplyable to a selector itsef, so something like:

$("table.special_to_be_sorted").bootstrapSortable(TRUE/FALSE, 'reversed',...);

You know?

**Comment by drvic10k** [comment]
now it should work also with $.bootstrapSortable(true)

**Comment by quemelol** [comment]
You're the man!
NOW it works as it is expected!
Thank you so much! That's a nice plugin, lightweight and works out-of-the-box. I felt pitty having to change it for something "so simple".
Nice work! All of it!
