### ISSUE TITLE
Sorting for dynamically added list

### ISSUE THREAD

**Issue by dheeraja00** [drvic10k/bootstrap-sortable#63]
Hi,
I have a table inside bootstrap model and the rows are populating by an ajax call which is fired on show event of model, here sorting is not working, always getting the error "Uncaught TypeError: Cannot read property 'replace' of undefined" on "v = v.replace(/^\s*/i, "").replace(/\s*$/i, "");" (minified script).

Please help to resolve it.

**Comment by drvic10k** [comment]
this is too little information

where is that error comming from? from the tiny-sort minified script? or from your code?

if it is from tiny-sort, you can download the full script and use it for debugging
