### ISSUE TITLE
Call a sort manually?

### ISSUE THREAD

**Issue by bdholmes** [drvic10k/bootstrap-sortable#66]
I have a scenario where the sortable table also has a feature of "Show More" where when the "Show More" link is clicked 25 more records are shown (initially 25 records are shown on initial page load).  When table headers are clicked to sort the table, the table should be sorted but also have the same amount of records being shown as on the previous sort (done last).  The problem I have is the table records are being hidden before first being sorted.  My workaround currently is to use a "settimeout" with the jQuery hide method inside of the function.  I was hoping to avoid using this hack and instead being able to somehow manually be able to call the table sort and then have the jQuery hidden method called on the appropriate number of records.  Is anyone aware of if this is possible and if so how?  Thanks!

**Comment by bdholmes** [comment]
![image](https://cloud.githubusercontent.com/assets/8834593/7683569/910aa356-fd45-11e4-8e54-53cd41daa8d9.png)

**Comment by drvic10k** [comment]
you can call `$.bootstrapSortable(true)` to sort the table with the previously applied sorting

**Comment by bdholmes** [comment]
Unfortunately this would call a sort with the previous sort that was completed.  I would need it to sort by the new sort field (or different sort direction).  The new sort field is the one captured in the click event above.  Unfortunately the setTimeout call seems to be the only workaround I've found to get the timing right (new sort completed and then to have the appropriate amount of records to be hidden).

**Comment by drvic10k** [comment]
there is currently no way for sorting from code, but I will keep this a a suggestion for new feature

**Comment by ideaoforder** [comment]
+1

**Comment by drvic10k** [comment]
now you can call $.bootstrapSortable({sortingHeader: element});

element is the `<th>` element that was supposedly clicked
