### ISSUE TITLE
Failed to execute 'querySelector' on 'Element': 'td:nth-child(NaN)' is not a valid selector.

### ISSUE THREAD

**Issue by krfa1** [drvic10k/bootstrap-sortable#67]
Hello,

I've installed bootstrap-sortable version 1.11.2 to sort date located on the bootstrap-table. I'm using bootstrap table 1.6.0. My content is a json array loaded through ajax .

When i'm clicking to sort the table on the any row, I receive this error message :
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': 'td:nth-child(NaN)' is not a valid selector.

I've correctly added moment.js, the css and js of bootstrap-sortable.

Following is my html table :
<table class="table no-margin sortable" id="table_invoice"></table>

And my javascript :

$(function () {
	$('#table_invoice').bootstrapTable({
	method: 'get',
	url: '/booking/invoices_json/',
	cache: false,
	search: true,
	striped: true,
	pagination: true,
	sortName : 'date',
	sortOrder : 'desc',
	pageSize: 5,
	onClickRow: function (row) {
		//if the user clicked on edit or remove, don't load the invoice form
		if (action != true) {
			window.location.href = '/mypage/otherpage/' + row.id +'/';
		}
	},
	columns: [
		{
				field: 'id',
				title: '{% trans "id"|capfirst %}',
				visible: false,
				sortable: true
		},
		{
				field: 'date',
				title: '{% trans "date"|capfirst %}',
				sortable: true
		},
		{
				field: 'status',
				title: '{% trans "status"|capfirst %}',
				sortable: true
		},
		{
				field: 'total',
				title: '{% trans "total"|capfirst %}',
				sortable: true
		},
	]
	});
});

**Comment by drvic10k** [comment]
did you set the correct date format for the cells?

**Comment by krfa1** [comment]
How do I do it? Because I'm retrieving cells value from a json, so I don't have any td or tr on my html code.

**Comment by drvic10k** [comment]
sorry, i'm not familiar with bootstrap table, but it seems to have its own sorting functionality
does that not work well lwith the dates?

**Comment by krfa1** [comment]
Nop, it doesn't sort the date well. I've tried to add the attribute data-dateformat to the td to work with bootstrap-sortable, but it still be the same issue.

**Comment by drvic10k** [comment]
even if you wouldn't specify the data-dateformat, it should just take it as regular strings and sort

that selector comes from tinySort, try replacing the minified sorter with the full one, so you can debug

**Comment by krfa1** [comment]
Just after your message I double check and find an other way with bootstrap-table to do it that I didn't find before. I only need to create a custom sorter, specified for the field. Thanks

**Comment by drvic10k** [comment]
no problem
