### ISSUE TITLE
table inside <table class="sortable">

### ISSUE THREAD

**Issue by bitonio** [drvic10k/bootstrap-sortable#68]
When adding a sub-table (on the client side, not existing during document ready event) in an existing sortable table cell, it inherits of the parent table class "sortable" CSS class and headers gets animated just if the sub-table was also sortable. So far, nothing to worry.

* If `$.bootstrapSortable()` is not invoked, no harm other misleading the end-user. Sort will not work on the sub-table.
* If `$.bootstrapSortable()` is invoked after the sub-table creation, a click on the sub-table header makes the parent table get sorted which is not really the intended effect.

I realize it is a corner case, but any way to tell the script to not apply sortable on sub table? Or even better: a way to get sub tables sortable.

**Comment by drvic10k** [comment]
fixed by #75
