### ISSUE TITLE
can i disable sorting on row

### ISSUE THREAD

**Issue by karwalbubble** [drvic10k/bootstrap-sortable#72]
Hi, 

This is really nice. It was quick to use this and add sorting on table.
I want to know if I can disable sorting on first row of table as in my first row, I have input fields which are used to add new entry. Meanwhile I am trying few options.

Thanks
Baljit

**Comment by karwalbubble** [comment]
resolved by removing row before sorting and adding it again after sorting.

**Comment by KrunchMuffin** [comment]
would be a nice option tho. I have totals on the last row and don't want to sort those.

**Comment by drvic10k** [comment]
i put Enhancement label on this, it might be useful

**Comment by KrunchMuffin** [comment]
on line 186 I tried adding `.not('tr:last');`, although the rows var didn't have it, it still sorted it.
