### ISSUE TITLE
Get the last row

### ISSUE THREAD

**Issue by Khrysller** [drvic10k/bootstrap-sortable#76]
Can i detect the last row no matter how many sorts i do?

Real case: Using a table with Bootstrap dropdown menu in a table responsive. so the dropdown menu always stay behind the table responsive. In the last row this is visible because it is the end of the table. So instead of using a dropdown I am gonna add the class `dropup` only for the last row. But as the user can sort N columns, how can I always get the last row no matter the sort?

http://jsfiddle.net/ot1o8aak/

Thanks all.
Thanks @drvic10k

**Comment by drvic10k** [comment]
Hi,
I think you can always get the last row from DOM

**Comment by Khrysller** [comment]
Thanks for the reply @drvic10k, but is it possible to get the last row no matter the sort I do? because i want to add the `dropup` class only in the last row, so every sort I do I need to find the last row and add `dropup` and remove `dropup` from the previous last row.

**Comment by drvic10k** [comment]
that will be the only solution, I think

**Comment by Khrysller** [comment]
yeah, people are help me here:

http://stackoverflow.com/questions/34184576/how-to-get-the-last-table-row-no-matter-the-sort/34185063?noredirect=1#comment56158796_34185063

and here:

http://stackoverflow.com/questions/34207170/how-to-run-a-function-after-an-external-js-script-finishes-running

If you have any toughts, could you please share? Thanks @drvic10k
