### ISSUE TITLE
Issue sorting date with time

### ISSUE THREAD

**Issue by KrunchMuffin** [drvic10k/bootstrap-sortable#77]
Is this even supported?

I have moment.js and my TH is like this

`<th data-dateformat="MM/DD/YYYY h:mmA">Date Submitted</th>`
and a sample TD
`<td>06/11/2016 11:00AM</td>`

you can see it doesn't sort properly
![image](https://cloud.githubusercontent.com/assets/1037197/11698271/bf9eaacc-9e8b-11e5-8d07-8747bc57e130.png)

**Comment by KrunchMuffin** [comment]
I think I may have it resolved. I added `data-value="2015-12-09 11:00AM"` to each TD and changed the dateformat to match and seems to sort ok. Must be the slash messing it up?

**Comment by KrunchMuffin** [comment]
Think I spoke too soon.  Not sorting times

![image](https://cloud.githubusercontent.com/assets/1037197/11699501/9d55edd4-9e92-11e5-92fb-ccf52a4ee875.png)

**Comment by KrunchMuffin** [comment]
nevermind. I am a tool. was putting dateformat on the TH not TD. be nice to be able to just have it on the TH tho.

**Comment by drvic10k** [comment]
I'm glad you solved it

Anyway, it's a good idea to have possibility to specify the format in header instead of each cell separately

**Comment by KrunchMuffin** [comment]
cool.
