### ISSUE TITLE
Adding sort icon on data-firstsort

### ISSUE THREAD

**Issue by KrunchMuffin** [drvic10k/bootstrap-sortable#79]
Is there a way to indicate which column was initially sorted on load? Not sorted via this plugin.
I would have thought that when using data-firstsort would do it but it does not appear to.

**Comment by drvic10k** [comment]
the `data-firstsort` tells the plugin, how to sort the column on first click
you can specify a column to be sorted on load by providing `data-defaultsort` attribute
