### ISSUE TITLE
Please add version to header.

### ISSUE THREAD

**Issue by KrunchMuffin** [drvic10k/bootstrap-sortable#80]
I have no idea which version I have since it is not listed in the header.

**Comment by drvic10k** [comment]
In what header?

**Comment by KrunchMuffin** [comment]
Of the Js and css files.

**Comment by drvic10k** [comment]
do you mean something like comment at the beginning of the file?

**Comment by KrunchMuffin** [comment]
Yes just like tinysort has. So we know what version we have compared to
what's available.

**Comment by bphilipnyc** [comment]
+1

**Comment by drvic10k** [comment]
added as 2.0.0, I will update bower and nuget
