### ISSUE TITLE
Incorrect sorting with col with rowspan

### ISSUE THREAD

**Issue by Khrysller** [drvic10k/bootstrap-sortable#81]
First, thanks again for this .js. It works great.
Recently I create a table with a rowspan and notice the sort wasn't work. It was sorting the next left column instead of the column clicked. Tried the last .zip here but still the same. The issue bellow says the same:

#52 

Can you take a look if you have a time? Thanks again.

**Comment by drvic10k** [comment]
can you make an example in [jsFiddle](https://jsfiddle.net/), please?

**Comment by drvic10k** [comment]
i will close the issue now, feel free to reopen it, but I will need some example where it doesn't work to be able to fix it (on the demo page it works correctly)
