### ISSUE TITLE
applyLast doesn't work

### ISSUE THREAD

**Issue by soisme** [drvic10k/bootstrap-sortable#83]
How does applyLast work? It doesn't remember my sort preference after I refresh the page or make a new ajax call. 

Is there a way to add the sort preference to cookie?

	$("table").on('sorted', function () {
		///add to cookie code here
	});

**Comment by drvic10k** [comment]
the sort preference is not kept after page refresh, but it should be after the ajax call

if you want to store the sorting state in cookie, look at the `lookupSortContext` function, you can get the context from the table the same way and store it in the cookie

**Comment by drvic10k** [comment]
did you solve it? can I close the issue now?

**Comment by soisme** [comment]
yea just close the issue.
