### ISSUE TITLE
New feature to your excellent script

### ISSUE THREAD

**Issue by zloystrelok** [drvic10k/bootstrap-sortable#85]
Hello!
Thank you very much for your excellent script. It's really easy to use and quite powerful.

Would you please add one tiny feature to it? 
I'm talking about optional first column with Line No., 1,2,3, etc. which will be constant in any sorting type.

**Comment by drvic10k** [comment]
hi,
currently you cannot set indices, but you can fix position of some rows by putting attribute `data-disable-sorting` on them. such rows won't be sorted then

does that cover your use case?

**Comment by zloystrelok** [comment]
Hello! I want to have first column with 1,2,3 no matter what sorting is applied to the table.
It's not about fixing position of rows.

**Comment by drvic10k** [comment]
so you mean that before sorting the rows are not first, second thirs, but after sorting, you want to have them in that order?

**Comment by zloystrelok** [comment]
i mean that i want to count rows visually, and I need first column with line nos. Want a screenshot?

**Comment by drvic10k** [comment]
yes please, I think I don't understand what you mean

**Comment by zloystrelok** [comment]
![image](https://cloud.githubusercontent.com/assets/5057430/13737495/e7989c2a-e9ce-11e5-8494-76c61607d9a2.png)

**Comment by drvic10k** [comment]
aha, so you want the column to be fixed, that's unfortunately not possible, because the sorting is done on rows as the smallest entity

there is an event triggered after the sorting, so you can hook on it and change the content of the first column after sorting

**Comment by zloystrelok** [comment]
Yes, exactly. I know that now there's no such functionality :)
What about implementing it in new version? :)

**Comment by drvic10k** [comment]
I'm affraid that it's not possible with how the sorting works

**Comment by zloystrelok** [comment]
Well', I'm done with these script:

```
$('#statTable').on('sorted', function () {
				var userListTable = document.getElementById('statTable');
				for (var i = 1; i < userListTable.rows.length; i++) {
					userListTable.rows[i].cells[0].innerText = i;
				}
			});
```

**Comment by drvic10k** [comment]
yes, that's what I meant
