### ISSUE TITLE
Sortable table inside a cell of another sortable table = KO

### ISSUE THREAD

**Issue by marcreig** [drvic10k/bootstrap-sortable#88]
Hi again...

sorry man, but I'm using your plugin since many months ago and I love it!

But every time I use it, I find things...

This time as I already said to you on last thread, a sortable table inside another sortable table, has 2 problems:

1) Parent table has one column with default-datasort="asc". Inner table too. Parent appears correctly sorted. Inner table, appears DESC sorted.
Having shoot on document.ready() the (and without it, happens the same, but symbols appears reversed to my point of understanding, you know... but problem is the same, bad sorting on inner table):

`$.bootstrapSortable({applyLast: false, sign: 'reversed'});`

2) When you sort parent table, inner table loses it's symbols. Keeps sorting always, but loses symbols.

There goes the Fiddle:

https://jsfiddle.net/d7r9fkdo/5/

Thanks for your time.

Mark.

**Comment by drvic10k** [comment]
indeed, the class is removed
I will have a look at it

**Comment by marcreig** [comment]
Class is problem 2.
But problem 1 is the "main" prob. What do you think about inversed sorting inside?

**Comment by marcreig** [comment]
So, have you test something more?

In my opinion there are currently 3 active issues on plugin:

1. "before-sort", not triggered on load time.
2. the inner sortable table inside another sortable table, loses header classes (pointers) when sorting through parent headers.
3. the inner sortable table inside another sortable table, having a column default-datasort="asc" and the parent one too, happens to appear sorted inversed. So parent appears ASC, but inner sortable tables appears DESC.

Is that ok?
I guess you can create a new version now... ;D

**Comment by drvic10k** [comment]
I am really happy, that you are interested in the plugin.
I am actively maintaining the plugin `in my free time`, but that is `limited`.

However, feel free to fork the repo and make a pull request.

**Comment by marcreig** [comment]
Good morning.

I only need to know if there's going to be an update soon.

Thanks.

**Comment by drvic10k** [comment]
sorry, no update soon

**Comment by marcreig** [comment]
Hey! So, no updates yet? 3 months has past already...

The only existing problem on my intranet app right now, is the 3 things commented before on top related with your sort plugin.

I need to know if you would finally update it or not, so I can change to another working plugin existing on the internet, in case you won't. Time ago, you used to mantain it cristal clear on a regular basis. I understand you have limited free time, but come on...

Kind reegards.
