### ISSUE TITLE
Sorting only being fired once

### ISSUE THREAD

**Issue by alexhobday** [drvic10k/bootstrap-sortable#93]
I have a table list that is being generated in the client using UnderscoreJS templates.

To trigger the Sortable plugin I'm running `$.bootstrapSortable(true);` after the template injection is complete.

However when I click on a heading column it sorts that column once but then will not sort it in the opposite direction when clicking again.

Looking in Inspector I see that it's always inserting the class `class="up sorted"`, I'm presuming this should alternate with `class="down sorted"`?

Am I missing something?

**Comment by drvic10k** [comment]
from what you wrote, it should work

so neither the icon nor the data is changing?

**Comment by drvic10k** [comment]
as there is no response, I am closing this

if the problem persist, please provide an example, where I can have a look at it
