### ISSUE TITLE
Sorting only works after page refresh/reload

### ISSUE THREAD

**Issue by vanhob** [drvic10k/bootstrap-sortable#95]
hi, sorting works perfectly but only after i refresh the page.  on the first load, the columns are clickable and the sorting order icons switch but rows are not actually sorted.

**Comment by drvic10k** [comment]
sorry I was quite inactive recently

did you manage to solve the problem? or can you provide an example that I can use for debugging?

**Comment by drvic10k** [comment]
i'm closing it, feel free to reopen the issue if you have more information
