### ISSUE TITLE
Rows not being removed

### ISSUE THREAD

**Issue by EverlessDrop41** [drvic10k/bootstrap-sortable#96]
I have a table which can be searched using an ajax request. Once the request is completed it updates the table using knockoutjs and calls `$.bootstrapSortable(true)`. Unfortunately it seems the new data is added to the table and the rest of the table is still there. removing the `sortable` class fixes the issue but obviously removes the sorting

**Comment by EverlessDrop41** [comment]
I fixed this by clearing the table body before adding the new data. This could've been a knockoutjs issue:

**Comment by AlexanderRodecape** [comment]
how did you do that?

**Comment by AlexanderRodecape** [comment]
Nevermind I just did this in my viewmodel to clear the table
$("#mytableID> tbody").html("");
