### ISSUE TITLE
Had uncaught SyntaxError:

### ISSUE THREAD

**Issue by AlexanderRodecape** [drvic10k/bootstrap-sortable#98]
I was getting this error in my knockout, breeze application with durandal.

uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': 'td:nth-child(NaN)' is not a valid selector

Adding '$.bootstrapSortable(true);' to the Durandal function, 'compositionComplete' of my view model fixed the issue.  compositionComplete is called when Durandal has completed composition of the entire page.

Just thought this might help someone one day.

Thanks for making this easy to install bootstrap sorting add-in,
Alex

**Comment by drvic10k** [comment]
thanks for sharing the experience, I labeled the "issue" as compatibility and I will close it
